default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: 'psqladmin'
  password: 'adminpass'
  host: localhost

development:
  <<: *default
  database: bull_and_bear_development

test:
  <<: *default
  database: bull_and_bear_test

production:
  <<: *default
  database: bull_and_bear_production
  host: ENV['PGHOST']
  username: ENV['PGUSER']
  password: ENV['PGPASSWORD']
  port: ENV['PGPORT']
